### ISSUE TITLE
official epel_repo_url appears to have changed

### ISSUE THREAD

**Issue by derekrspencer** [geerlingguy/ansible-role-repo-epel#12]
Tried to run one of my ansible scripts today that uses this role and it failed because it couldn't find the epel-release rpm.  I noticed the official fedora epel wiki directs people to https://dl.fedoraproject.org now instead of http://download.fedoraproject.org.  I changed it and everything is working as it should again.

**Comment by geerlingguy** [comment]
Above PR was merged.
