### ISSUE TITLE
unable to re-generate /etc/yum.repos.d/epel*.repo file

### ISSUE THREAD

**Issue by shamimgeek** [geerlingguy/ansible-role-repo-epel#19]
if /etc/yum.repos.d/epel.repo or /etc/yum.repos.d/epel-testing.repo removed. 

This playbook is unable to re-generate the files.

**Comment by geerlingguy** [comment]
@shamimgeek - What are the steps to reproduce this issue? Did you run the role, then manually SSH into the server, delete those files, then try to run this role again?

The role simply uses Ansible's `yum` module (https://github.com/geerlingguy/ansible-role-repo-epel/blob/master/tasks/main.yml#L7) to download/install the EPEL rpm, and that's about it... it's meant to install the repo if it's never been installed before, but I don't have any guarantees of what will happen if it's run on a broken server...

**Comment by shamimgeek** [comment]
To re-produce this issue : 
 - I deleted those two files after then i executed role again. but it was not updating the files. 
 - if i remove the epel rpm manually then try it is working.

**Comment by geerlingguy** [comment]
@shamimgeek - If you're controlling the server entirely via automation, then that file should not be modified by hand. It's a similar situation to how my other roles install a package, but if you manually modify the package, I can't expect to still cleanly manage the package.

This role's purpose is only to install the RPM, and not necessarily take over the files that are placed on the filesystem by the RPM.

The intention as that this is the only role that would be managing EPEL—and if you have a more specialized case where you need to be able to delete/re-add/template the .repo files, then I would recommend either forking this role and modifying it to suit your needs or building a separate role that does exactly what you need.
