### ISSUE TITLE
Wrong detection if EPEL repo enabled

### ISSUE THREAD

**Issue by m-abramovich** [geerlingguy/ansible-role-repo-epel#22]
Code checks only if file exists:
`- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
`
But sometimes (for example, on Amazon Linux distro) it exists but not enabled.
Can be solved maybe [this way](https://github.com/ansible/ansible-modules-extras/issues/2384).

**Comment by MichaelLeeHobbs** [comment]
Same issue I think. Using Amazon Linux 2

TASK [geerlingguy.repo-epel : Install EPEL repo.] ************************************************************************************************************************************************************************************************************
fatal: [swarm-02]: FAILED! => {"msg": "The conditional check 'result.rc == 0' failed. The error was: error while evaluating conditional (result.rc == 0): 'dict object' has no attribute 'rc'"}
fatal: [swarm-01]: FAILED! => {"msg": "The conditional check 'result.rc == 0' failed. The error was: error while evaluating conditional (result.rc == 0): 'dict object' has no attribute 'rc'"}
        to retry, use: --limit @/root/dockerSwarm/playbook.retry

**Comment by MichaelLeeHobbs** [comment]
This works of AWS Linux 2 for anyone that finds this.

    - name: Install EPEL repo on AWS Linux 2
      yum:
         name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
         state: present
