### ISSUE TITLE
Install EPEL Task Broken in Ansible 2.5

### ISSUE THREAD

**Issue by mattmonkey83** [geerlingguy/ansible-role-repo-epel#26]
There appears to be a change in loop conditionals in Ansible 2.5 - https://github.com/ansible/ansible/issues/37980

The install of the epel package works but the conditional fails, leading to retries and eventually a failure of the task.

Changing this line should resolve - https://github.com/geerlingguy/ansible-role-repo-epel/blob/master/tasks/main.yml#L11

**Comment by mattmonkey83** [comment]
Just spotted a related PR has been raised - https://github.com/geerlingguy/ansible-role-repo-epel/pull/25

**Comment by geerlingguy** [comment]
That PR has been merged (https://github.com/geerlingguy/ansible-role-repo-epel/pull/25), and I tagged a new release of the role—1.2.3—and this is now resolved. Just tested on my local machine and it worked for me!
