### ISSUE TITLE
Docker image already has EPEL installed

### ISSUE THREAD

**Issue by deekayen** [geerlingguy/ansible-role-repo-epel#28]
If I'm reading the Travis output correctly, the tests aren't actually getting to try installing the EPEL repo because the Docker image already has it. The step to install EPEL is skipped on the initial and idempotence re-run.

https://travis-ci.org/geerlingguy/ansible-role-repo-epel/jobs/369346957

**Comment by geerlingguy** [comment]
D'oh! Well at least it tests the idempotence _really_ well. Not much I can do right now as that's how Ansible's installed inside the container. It's kind of like the Ansible role tests... Ansible is already there, so it's more just testing that the playbook functions correctly.
