### ISSUE TITLE
The conditional check 'result.rc == 0' failed

### ISSUE THREAD

**Issue by leonardodavinte** [geerlingguy/ansible-role-repo-epel#30]
TASK [repo-epel : Install EPEL repo.] ********************************************************************************************************************************************************
fatal: [192.168.0.50]: FAILED! => {"msg": "The conditional check 'result.rc == 0' failed. The error was: error while evaluating conditional (result.rc == 0): 'dict object' has no attribute 'rc'"}

**Comment by ynixon** [comment]
changing 
```until: result.rc == 0```
to
```until: : result is succeeded```
Should do the work

**Comment by leonardodavinte** [comment]
> changing
> `until: result.rc == 0`
> to
> `until: : result is succeeded`
> Should do the work

Thank you so much @ynixon

**Comment by geerlingguy** [comment]
PR merged, new tag is up, thanks!
