### ISSUE TITLE
Not a valid key /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7

### ISSUE THREAD

**Issue by valugi** [geerlingguy/ansible-role-repo-epel#47]
Seems that the default key is not valid anymore, maybe is related with the latest changes.
Happens on Centos7 using ansible 2.9.6.
`

28-Sep-2020 00:16:30 | amazon-ebs: TASK [geerlingguy.repo-epel : Import EPEL GPG key.] ****************************
-- | --
28-Sep-2020 00:16:31 | amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "msg": "Not a valid key /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7"}

`

**Comment by geerlingguy** [comment]
I just released a new version of this role yesterday (see https://github.com/geerlingguy/ansible-role-repo-epel/releases/tag/3.0.0) with a fix for this—please see if updating the role to the latest version fixes the problem for you. If not, feel free to reopen the issue. Thanks!
