### ISSUE TITLE
Use the permanent urls

### ISSUE THREAD

**Issue by rahulsundaram** [geerlingguy/ansible-role-repo-epel#9]
Hi

 * http://dl.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm
 * http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
 * http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

Also note that CentOS already ships with EPEL repo rpm.  yum install epel-release should work

**Comment by geerlingguy** [comment]
For simplicity's sake (since I want this role to be compatible with EPEL 5/6 until their EOLs, I'll stick with these URLs for now. Someday when 6 is not supported anymore, I'll switch to the yum installation :)

**Comment by rahulsundaram** [comment]
I am not sure you read the change.  It doesn't change anything except the urls.    please take a look again.

**Comment by rahulsundaram** [comment]
Right.  This role should work on EPEL + CentOS 7 as well. and switching the yum installation won't work for EPEL 7 + RHEL 7 anyway afaik.  Lets revisit later if necessary.
